"""Application-level constants for the feature-switching GUI."""

LIST_SHOW_LIMIT = 500000
META_PROGRESS_EVERY = 1000

DEFAULT_WINDOW_WIDTH = 1680
DEFAULT_WINDOW_HEIGHT = 980
DEFAULT_TARGET_EXPERIMENT_ID = 43003

DEFAULT_FEATURE_KEY = "dRdt"
DEFAULT_SHOW_RAW = True
DEFAULT_HIDE_PURPLE = True
DEFAULT_LOG_R = False
